ARG  VER=latest
FROM ubuntu:${VER}

WORKDIR /root

COPY ssh/id_ed25519.pub .ssh/authorized_keys

RUN set -ex &&\
    chmod 700 ~/.ssh &&\
    chmod 600 ~/.ssh/authorized_keys &&\
    apt-get -qq update &&\
    DEBIAN_FRONTEND=noninteractive apt-get -yqq --no-install-suggests --no-install-recommends install \
      openssh-server \
      > /dev/null &&\
    rm -rf -- /var/lib/apt/lists/* /var/cache/apt/* &&\
    mkdir -p /var/run/sshd
    # printf 'github.com,192.30.255.112 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==' \
    #   >> ~/.ssh/known_hosts

CMD ["/usr/sbin/sshd", "-D"]
